package io.vidocq.tools.lc4jcdi.mcptasks;

import jakarta.data.repository.BasicRepository;
import jakarta.data.repository.Repository;
import java.util.List;

/**
 * The {@code task_events} table, as a Jakarta Data repository generated by Mansart. Not {@code @Transactional},
 * for the reason given on {@link TaskRepository}.
 */
@Repository
public interface TaskEventRepository extends BasicRepository<TaskEvent, Long> {

    /**
     * The history of a task.
     *
     * @param taskId the task id; its events stay after the task is deleted
     * @return the events, oldest first
     */
    List<TaskEvent> findByTaskIdOrderByIdAsc(Long taskId);
}
