-- V1: the task tracker schema, applied by the Flyway migration extension to the @Default datasource.
-- Identifiers are quoted and lower-case, as Mansart Data quotes the table and column names it derives.

CREATE TABLE "tasks" (
  "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"        VARCHAR(200)  NOT NULL,
  "description"  VARCHAR(2000),
  "project"      VARCHAR(80)   NOT NULL,
  "status"       VARCHAR(10)   NOT NULL,
  "priority"     VARCHAR(10)   NOT NULL,
  "due_date"     DATE,
  "created_at"   TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at"   TIMESTAMP WITH TIME ZONE NOT NULL,
  "completed_at" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "tasks_status_ck"   CHECK ("status"   IN ('OPEN', 'DONE')),
  CONSTRAINT "tasks_priority_ck" CHECK ("priority" IN ('LOW', 'MEDIUM', 'HIGH'))
);
CREATE INDEX "tasks_status_due_idx" ON "tasks" ("status", "due_date");
CREATE INDEX "tasks_project_idx"    ON "tasks" ("project");

-- Audit trail written in the same transaction as the task change; kept when a task is deleted (no FK).
CREATE TABLE "task_events" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id"     BIGINT       NOT NULL,
  "type"        VARCHAR(20)  NOT NULL,
  "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "detail"      VARCHAR(500)
);
CREATE INDEX "task_events_task_idx" ON "task_events" ("task_id", "id");
